[[redirects]]
  from = "https://compassionate-raman-f6c431.netlify.com/*"
  to = "https://rastamozhka2019.co.ua/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://compassionate-raman-f6c431.netlify.com/*"
  to = "http://rastamozhka2019.co.ua/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://rastamozhka2019.co.ua/*"
  to = "https://rastamozhka2019.co.ua/:splat"
  status = 301
  force = true